### ISSUE TITLE
Changes produce broken video

### ISSUE THREAD

**Issue by davitf** [anthwlock/untrunc#1]
Hi! As you requested in [my pull request](https://github.com/ponchio/untrunc/pull/117), I've uploaded a sample video which is fixed correctly by ponchio's master, but when I run it on your master, the output is a broken video. [Here are the files.](https://drive.google.com/open?id=1T3lNRprabirOEl-Iy3OO95L35RrGssZ-)

Running:
`./untrunc ok.mp4 broken_sample.mp4`

The original code produces the file I've renamed `output_original.mp4`, and this version produces `output_corrupted.mp4`.

Let me know if I can help!

**Comment by anthwlock** [comment]
The problem is that the SPS Unit needs to be decoded before the slices are. I added default values for the SpsInfo but this is only a quick fix. Please try if it works for you now.

**Comment by davitf** [comment]
It worked! It seemed that the output file was larger than the one generated by ponchio's original code, but I haven't really stopped to analyze.
