### ISSUE TITLE
Got unexpected packet size after a partial decode

### ISSUE THREAD

**Issue by jrichardsz** [anthwlock/untrunc#10]
I tried to use this tool to restore my broken mp4 video but , I have this error:

```
Info: reading /path/to/working-video.m4v
Info: parsing healthy moov atom ... 
Info: avcC got decoded
Info: parsing mdat from truncated file ... 
[aac @ 0x10da980] Multiple frames in a packet.
[aac @ 0x10da980] Got unexpected packet size after a partial decode
Error: Invalid length: -22. Wrong match in track: 0
Error: unable to find correct codec -> premature end
Info: Found 1 packets ( mp4a: 1 avc1: 0 avc1-keyframes: 0 )
Info: Duration of mp4a: 21ms  (21 ms)
Info: Duration of avc1:  (0 ms)
Info: saving /path/to/broken-video.mp4_fixed.mp4
```

I have cloned the last version (master) and follow the readme instructions.

Please, what can I do?

Regards.

**Comment by anthwlock** [comment]
Try other versions of libavcodec. For example 3.2.11.
I think you have the same problem as described [here](https://github.com/anthwlock/untrunc/issues/5).
Please tell me which version worked for you after you are done.

**Comment by jrichardsz** [comment]
I will try , thanks!
