### ISSUE TITLE
Support for MTS?

### ISSUE THREAD

**Issue by auanasgheps** [anthwlock/untrunc#101]
Hello,

I have videos recorded by a Sony camera which I would like to repair.
They're just AVC video and AC3 audio.

Would be possible to support this kind of file? 
![image](https://user-images.githubusercontent.com/20586878/133473108-a5e9e0f0-9a3c-4d53-8557-c6cfc6d16198.png)
I'm trying to analize a reference file, but I get the following error.
![image](https://user-images.githubusercontent.com/20586878/133473466-c53105fd-b06e-4f42-a5df-ed11f96f77f6.png)

Thanks

**Comment by anthwlock** [comment]
Hey,

As you have noticed, untrunc currently only supports the [mp4 container](https://en.wikipedia.org/wiki/MPEG-4_Part_14) format, so the [m2ts container](https://en.wikipedia.org/wiki/.m2ts) format is (currently) not supported.

Have you tried other tools already? After a quick search I found this: https://forum.videohelp.com/threads/339721-Scanning-and-fixing-m2ts-file-errors#post2112569

If you send me your files I will take a look.

Related issue: https://github.com/ponchio/untrunc/issues/203

**Comment by auanasgheps** [comment]
Hi, sorry for the late reply. 
TS Doctor is able to fix some of these files.
Thanks!
