### ISSUE TITLE
Could not create file for writing

### ISSUE THREAD

**Issue by timsamsPoly** [anthwlock/untrunc#109]
Hello,

I'm on win10 using the gui version of untrunc and there is no way for me to finish the process.
Everytime it says "Could not create file for writing"

I am running the soft as admin, saving in the same folder and other folder, always the same problem.

I don't know what to do because my files seems to be correctly decrypted but since the software can't save them, it goes to trash.

Do you have any idea what to do ?

**Comment by anthwlock** [comment]
Does it create a (maybe empty) file at all? Is there enough free space on the disk? Can you create a new file manually? In case your file paths contain non-ascii characters, try to rename them (however this should in theory not be a problem anymore, see #81). Maybe try to disable any AV?

**Comment by anthwlock** [comment]
With 5905c968a9d469c3b15d67adc14a9324cfbf2b5e the corresponding system gets appended to the error message. Maybe this provides some insights.

**Comment by anthwlock** [comment]
With 47b4846d824d7c73c3973f414463c46f017a2fa1 the corresponding system gets appended to the error message. Maybe this provides some insights.

**Comment by anthwlock** [comment]
Does it create a (maybe empty) file at all? Is there enough free space on the disk? Can you create a new file manually? In case your file paths contain non-ascii characters, try to rename them (however this should (in theory) not be a problem anymore, see #81). Maybe try to disable any AV?

With 47b4846d824d7c73c3973f414463c46f017a2fa1 the corresponding system gets appended to the error message. Maybe this provides some insights.

**Comment by timsamsPoly** [comment]
I tried it all then you mentionned the AV. Goddamn Avast !
Problem solved, thanks a lot for contributing to that awesome project. you are my savior ^^
