### ISSUE TITLE
'make' goes with failure on Arch Linux

### ISSUE THREAD

**Issue by abdulbadii** [anthwlock/untrunc#121]
How is the solution of this failure on Arch Linux
```

src/codec.cpp: In function ‘int untr_decode_audio4(AVCodecContext*, AVFrame*, int*, AVPacket*, uint)’:
src/codec.cpp:341:24: error: ‘avcodec_decode_audio4’ was not declared in this scope; did you mean ‘untr_decode_audio4’?
  341 |         int consumed = avcodec_decode_audio4(avctx, frame, got_frame, pkt);
   
```
and line 361, please help out guide to correct way

**Comment by domino-pl** [comment]
Yeah, I think this function was removed as deprecated:
https://www.ffmpeg.org/doxygen/3.3/group__lavc__decoding.html#gaaa1fbe477c04455cdc7a994090100db4

**Comment by broes5** [comment]
Can the deprecated function used in untrunc be swapped out with a new one that does the same thing?

**Comment by davidebeatrici** [comment]
See https://stackoverflow.com/questions/68240679/avcodec-decode-audio4-was-deprecated-how-can-i-decode-the-audio-frame-of-size-a.
