### ISSUE TITLE
Can you upload new Releases?

### ISSUE THREAD

**Issue by qingchunnh** [anthwlock/untrunc#126]
I don't know how to build, but I really need untrunc_x64.Thank you!

**Comment by Allofich** [comment]
There is an uploaded release at https://github.com/anthwlock/untrunc/releases.
Click "Assets" and you can see them.

**Comment by artenax** [comment]
For Linux 32 bit you can download here https://github.com/artenax/untrunc/releases

**Comment by qingchunnh** [comment]
> [在https://github.com/anthwlock/untrunc/releases](https://github.com/anthwlock/untrunc/releases)上有上传的版本。 单击“资产”，您可以看到它们。

Thank you very much

**Comment by qingchunnh** [comment]
> 对于 Linux 32 位，您可以在此处下载https://github.com/artenax/untrunc/releases

Thank you very much
