### ISSUE TITLE
Couldn't open reference file

### ISSUE THREAD

**Issue by Ferlo-0671** [anthwlock/untrunc#154]
I have just downloaded it and tried to use it, but every time I try to repair a video it says "Couldn't open file"..."No such file or directory"
![Captura](https://github.com/anthwlock/untrunc/assets/160298502/2d2bf011-1861-4411-990a-365ac09b12ec)
¿What am I doing wrong?

**Comment by llvs** [comment]
Just a guess: Try to avoid space characters in path and filename.
