### ISSUE TITLE
Please describe this fork in README

### ISSUE THREAD

**Issue by vitaly-zdanevich** [anthwlock/untrunc#16]
I mean - what the difference from https://github.com/ponchio/untrunc

**Comment by anthwlock** [comment]
Good idea, I added [some points](https://github.com/anthwlock/untrunc#about-this-fork).
How did you find this fork? I guess by an open issue over on ponchio's untrunc?

**Comment by vitaly-zdanevich** [comment]
Yes, about impossible compilation.
