### ISSUE TITLE
windows build question

### ISSUE THREAD

**Issue by brentjohnston** [anthwlock/untrunc#20]
Hi I am the guy that you helped with the windows build. I got the file working but the last 2 minutes of the video or so is frozen. Just wondering if there might be some command line varibles I can type in to get those last 2 minutes.

Also I did notice that the audio is not synced and wasn't sure how to fix it. I have to say I am still very happy but just wondering if you might have an idea. Just got back and donated btw. :)

**Comment by anthwlock** [comment]
Thank you for donating!
Does untrunc output anything suspicious, or does it end normally?
If latter, I guess that either the audio or the video is played at a wrong speed.
You could try to use another healthy file. In case the video seems to be too fast, it would be possible to fix this by manipulating the values in the 'stts' atom of the video track. AFIK this is not possible with the audio, it requires re-encoding.
Let me know if you notice such a wrong speed, either in audio or in video. 
Or maybe you are sure that some pictures are missing?

**Comment by anthwlock** [comment]
I added an option `-sv` to manipulate the 'stts' values as I said above.
If you have further questions, please open another Issue or reactivate this one
