### ISSUE TITLE
Windows and Debian - untrunc does not finish

### ISSUE THREAD

**Issue by EQWorry** [anthwlock/untrunc#21]
Hi, both under Windows and Debian untrunc prints out some info but then hangs forever (uh) at:
`Info: Found 498 packets ( avc1: 498 avc1-keyframes: 50 )`
With other files the similar happens:
`Info: Found 122 packets ( avc1: 122 avc1-keyframes: 14 )`
It uses some CPU power, but does nothing for hours now. Any help/suggestions much appreciated.

**Comment by EQWorry** [comment]
Suggesting @ myself: Could this behavior be caused by the fact that neither the corrupted and the correct file contain audio track, only video? Files with audio get processed...

**Comment by asos-krystian** [comment]
I have the same problem on my mac. The original version (by @ponchio) works fine but I need support for larger files. @EQWorry I can also confirm that my files are without audio track.

**Comment by anthwlock** [comment]
Hey, I think it should work now, after this [commit](https://github.com/anthwlock/untrunc/commit/3724983cd2b)!

**Comment by EQWorry** [comment]
Great job, thanks a lot, it works now even on files with no audio! :-)
