### ISSUE TITLE
Cant configure

### ISSUE THREAD

**Issue by ulist** [anthwlock/untrunc#24]
[log.txt](https://github.com/anthwlock/untrunc/files/3214080/log.txt)

**Comment by anthwlock** [comment]
What setup/compiler/ffmpeg do you use? (`uname -a`, `g++ --version`, `ffmpeg -version`)
If you are using ffmpeg < 3.1, try `make FF_VER=3.3.9`, as described [here](https://github.com/anthwlock/untrunc#with-local-libraries).

**Comment by ulist** [comment]
```
Linux localhost 3.10.86-g0c14827 #2 SMP PREEMPT Thu Jul 12 13:13:34 CST 2018 aarch64 Android
====
clang version 8.0.0 (tags/RELEASE_800/final)
Target: aarch64-unknown-linux-android
Thread model: posix
InstalledDir: /data/data/com.termux/files/usr/bin
```
I use the static build
```
'
$ ffmpeg -version
ffmpeg version N-48875-g58d167bcd5-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
```

**Comment by anthwlock** [comment]
Hmm, and what compiler are you using?
In your log it says:
> codec.cpp:247:43: error: no member named 'channels' in 'AVFrame'

But from ffmpeg version [2.0](https://ffmpeg.org/doxygen/2.0/structAVFrame.html) to current [nightly](https://ffmpeg.org/doxygen/trunk/structAVFrame.html) 'channels' is indeed a member of AVFrame!

Where do you get the API-Headers from?
It looks like https://johnvansickle.com/ffmpeg/ only publishes the final executables, not the static libs?

**Comment by anthwlock** [comment]
closing because inactive.
