### ISSUE TITLE
Compile statically?

### ISSUE THREAD

**Issue by sammarks** [anthwlock/untrunc#32]
Are there any configuration preferences for the makefile to compile this statically?

**Comment by anthwlock** [comment]
Just use `make FF_VER=3.3.9`

**Comment by sammarks** [comment]
I'm building it to run inside AWS Lambda, so unfortunately can't install all of the required shared libraries inside their execution environment before running this.

That's the build step I'm using at the moment, and am running into this error when executing inside Lambda:

```
error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
```

**Comment by anthwlock** [comment]
Hmm.. finding the missing library can be quite cumbersome..

What about writing a little script which copies every shared library which untrunc needs to your deploy folder? That's what I [did](https://github.com/anthwlock/untrunc/blob/a9a101ef7d3e76c8b3bd82f6474070352c9dd777/.appveyor.yml#L67) for the windows builds. 
Instead of using `depends` you could use `ldd`.

You should probably filter ldd's output though, as libraries like `libc` should alredy exist..

**Comment by sammarks** [comment]
Thanks for the info! I'll try and modify that and see where I end up.

I have a bunch of MP4 fragments (basically just chunks of a bigger MP4 file, split apart and uploaded to S3 individually), and the Lambda concatenates all of them together very simply, and then runs the final result through `untrunc` to restore the required metadata, timecodes, etc to get a playable MP4 file.

And mostly just using Lambda as opposed to a Docker container for pricing reasons. Much cheaper to run it this way since I only have to pay for the seconds that I use.

**Comment by sammarks** [comment]
That did the trick! I ended up having to go back to the original fork of the project - it worked for the particular videos I'm uploading, and the new fork throws errors about multiple frames in the same packet (looks like it's coming from AAC).

For reference, here are the relevant lines on the Dockerfile:

```docker
RUN mkdir /untrunc-dist && cp untrunc /untrunc-dist
WORKDIR /untrunc-dist
RUN ldd untrunc | grep -Po "(?<= \=\> )[^(]+(?=\(0x)" > depfiles.txt
RUN bash -c 'while read -r line; do cp -v $line ./; done <<<$(cat depfiles.txt); exit 0'

# Remove unnecessary untrunc shared libraries for Amazon Linux.
RUN rm -v depfiles.txt libc.so.6 libgcc_s.so.1 libm.so.6 libpthread.so.0 libstdc++.so.6 libz.so.1
```

I also modified the Dockerfile to do the building inside an Amazon Linux box instead of Ubuntu (so had to change the `apt-get` calls to their `yum` equivalents).

Then just modified my code to package that up with the Lambda, and used `LD_LIBRARY_PATH` whenever running `untrunc` inside the Lambda.

**Comment by anthwlock** [comment]
Great!

The `[aac @ 0x55e00a329300] Multiple frames in a packet.` shouldn't be a problem though. It is handled and explained [here](https://github.com/anthwlock/untrunc/blob/a9a101ef7d3e76c8b3bd82f6474070352c9dd777/src/codec.cpp#L236):
> // ffmpeg 3.4+ uses internal buffer which needs to be updated.
> // this is slow because of the internal memory allocation.
> // ff34+ decodes till exhaustion, which in turn spams repetitive warnings/errors

It should output the following directly after the 'Multiple frames' message:
> Info: Muted ffmpeg to reduce redundant warnings/errors. Use '-v' to see them.

If you don't mind create a new issue, with the full output, combined with `untrunc -i <ok.mp4>`.

FYI, the original untrunc loads the whole file into RAM, which can be quite [a problem](https://github.com/ponchio/untrunc/issues/30#issuecomment-143744821)..

**Comment by sammarks** [comment]
I start working on this again on Thursday of this week - I will get that output for you then and post it back here.

**Comment by anthwlock** [comment]
apparently not

**Comment by fedexman** [comment]
Just posting here if anyone needs. I was able to build a static untrunc binary specifically for the python3.13 lambda runtime 🙏 it's working really well !
Info how to build the binary in the readme:
https://github.com/scoville/untrunc_lambda
