### ISSUE TITLE
invalid atom name: 'drm ' +  skip audio

### ISSUE THREAD

**Issue by paqio** [anthwlock/untrunc#33]
The space is clearly the issue. I removed the check and it went further.

Yet now there is another issue: "This audio codec is EVIL, there is no hope to guess it". Is there a way to skipp audio?

**Comment by anthwlock** [comment]
If there is _really_ no way to guess it's size, one possibility is to search the beginning of the video codec. For example h264 often starts with '0x000001' and so on..
Btw this logic is already implemented for 'unknown sequences', see `Mp4::unknown_length_` and its usage.
If you need further help please send me the broken and healthy videos!
Maybe there is a way to guess the size. That would be the best solution.

**Comment by anthwlock** [comment]
[relevant](https://github.com/anthwlock/untrunc/issues/31#issuecomment-534185772).
