### ISSUE TITLE
 error: use of undeclared identifier '__gcd'; note that Makefile uses c++11 (and not c++17)

### ISSUE THREAD

**Issue by GwynethLlewelyn** [anthwlock/untrunc#36]
Hello,

First of all, thanks so much for your port of `untrunc`, having a 'real' Makefile makes all the difference! 😄
I'm compiling under macOS Catalina 10.15.1 (Beta), using XCode 11.1, as well as `brew`to install `libav`, and I'm getting the error listed on the subject. According to [this](https://stackoverflow.com/questions/52906184/why-gcd-is-throwing-error-in-macos-mojave), there are two issues that require fixing:

1. Do _not_ use `__gcd()` — while it's common usage, it's supposed to be a private, internal function. Use `gcd()` instead.
2. `gcd()` is available under `c++17`, but your Makefile uses `c++11`.

Both fixes are actually very easy to do (even for someone who has not programmed in C++ for almost two decades, like me! 😲)

**Comment by Andz200zx** [comment]
thanks for posting the solution to this, it meant I could get mine to work last night! there's a fork of this on my page that got it working fine on my Mojave machine using your suggestions if anyone needs it. also many thanks @anthwlock, this has saved some videos I was really struggling to recover!

**Comment by anthwlock** [comment]
thanks for reporting, fixed in 51ebdc1cf.
