### ISSUE TITLE
Error: bad track: 'mp4v'

### ISSUE THREAD

**Issue by edent** [anthwlock/untrunc#37]
I'm trying to fix a broken 3GP file. I have a couple of working files from the same camera. When I run `untrunc` I get this error.

```
Info: version '' using ffmpeg '4.1.3-0ubuntu1'
Info: reading /data/working.3GP
Info: parsing healthy moov atom ... 

Info: unknown track 'mp4v' found -> fallback to dynamic stats
Error: bad track: 'mp4v'
```

Any idea what I can do to fix it?

**Comment by zrose584** [comment]
See [this](https://github.com/anthwlock/untrunc/blob/51ebdc1cfb22577f43041d67714fee492be0f94f/src/codec.cpp#L377) function? One needs to implement it.
If you get it to work, please make a PR.
I can only help you if you give me the pair of files (working+broken)!

**Comment by anthwlock** [comment]
See [this](https://github.com/anthwlock/untrunc/blob/51ebdc1cfb22577f43041d67714fee492be0f94f/src/codec.cpp#L377) function? One needs to implement it.
If you get it to work, please make a PR.
I can only help you if you give me the pair of files (working+broken)!

**Edit:**
It looks like some effort was alredy done for this: https://github.com/Hacklin/untrunc/commit/cb2d05d075778d151c2efd1e6632528c1910f9d2.

**Comment by anthwlock** [comment]
@edent 
I added said function, however it will (currently) only work when [building against](https://github.com/anthwlock/untrunc#with-local-libraries) ffmpeg 3.3.
If interested, read [here](https://github.com/anthwlock/untrunc/blob/4f7098376fe9835b06df0d5eab86b282890d33f0/src/codec.cpp#L285) why.

Hope it works now!
