### ISSUE TITLE
various errors when fixing mp4

### ISSUE THREAD

**Issue by jambo2020** [anthwlock/untrunc#38]
Running the dockerfile untrunc. Ran into some errors when repairing an mp4

mp4a: Success for no particular reason....
Duration: 0
avc1: No match because of NAL type: 27

Track 0 codec: mp4a
[aac @ 0x1f8fac0] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x1f8fac0] Reserved bit set.
[aac @ 0x1f8fac0] Prediction is not allowed in AAC-LC.

Repair: /mnt/bad1.MP4
Track 0 codec: mp4a
Track 1 codec: avc1
First byte expected 0.
mp4a: Failure because of NULL header.
avc1: Match with 0 header.

Would appreciate some help - taken me forever just to get the dockerfile to work correctly

**Comment by anthwlock** [comment]
I can see from the output that you are using ponchio's untrunc.
Please try this fork, if it doesn't work, send me the files.

Good luck.

**Comment by jambo2020** [comment]
I'm trying to install this fork but... The with systems library part, what do I need for # get the source code?   I try with local libraries and get : No targets specified and no makefile found.  Stop. At the make FF_VER=3.3.9 Part.    Trying to install via your docker file instructions and get this error at the first line:  unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/pi/Dockerfile: no such file or dir

**Comment by anthwlock** [comment]
> what do I need for # get the source code? I try with local libraries and get : No targets specified and no makefile found.

It literally means that you should get the source code.
If you have git, you can do `git clone https://github.com/anthwlock/untrunc; cd untrunc`
Otherwise you can download the repo as .zip by clicking on `Clone or download`.

Btw, if you have windows, there are [prebuild releases](https://github.com/anthwlock/untrunc/releases). Just in case you didn't notice.

**Comment by anthwlock** [comment]
closing since inactive
