### ISSUE TITLE
Error: bad track: 'mebx'

### ISSUE THREAD

**Issue by LuminolBlue** [anthwlock/untrunc#47]
Hi there, 
I've tried using on both windows and linux. I wasn't able to recover my files due to an error:
~~~~~~~~~~~~~~~
Info: version '' using ffmpeg '3.3.9'
Info: reading good_file.mp4
Info: parsing healthy moov atom ... 
Sample dependency flag atom found. I and P frames might need to recover that info.
Info: special track found (meta, 'Core Media Metadata')
Info: special track found (meta, 'Core Media Metadata')

Info: unknown track 'mebx' found -> fallback to dynamic stats
Error: bad track: 'mebx'
~~~~~~~~~~~~~~~

Can you tell me what this means? I'm not sure why it doesn't work, I've followed all instructions and compiled correctly. on the gui version the it crashes when I click 'repair' this error was taken from terminal not sure if that affects anything.

Please help me out, thanks!

**Comment by anthwlock** [comment]
If you send me the files (healthy+broken) I will take a look.
You can upload them on [wetransfer](https://wetransfer.com/).
If you think they are too big, use `untrunc -sh file.mp4`.

**Comment by anthwlock** [comment]
> Can you tell me what this means?

see https://github.com/ponchio/untrunc/issues/182#issuecomment-611465949.

I will close this since the I received no files.
Once someone has send me a pair of files (healthy+broken) this can be reopened

**Comment by KarimEZ** [comment]
I'm sending you a pair of files so you can give it a try. Thx!

**Comment by anthwlock** [comment]
@KarimEZ I made some [commits](https://github.com/anthwlock/untrunc/commit/b170c35b9de6cdce6ba39dbc6c7df949f635d2af), it should work now.
