### ISSUE TITLE
Add output directory switch please

### ISSUE THREAD

**Issue by jpooley-hearst** [anthwlock/untrunc#48]
Hi, 

Thanks for doing this and making a Windows build! Could you please add a switch or argument to define the output directory or file? This will allow the program to be used more easily in an automated fashion.

**Comment by anthwlock** [comment]
Done in https://github.com/anthwlock/untrunc/commit/71d1a6556205f67f77114f667785c84922bc01f9. Hope it works on all platforms.
Btw, that commit also adds a `-skip` switch.
