### ISSUE TITLE
Sample file from RTMP recorder 

### ISSUE THREAD

**Issue by mkrn** [anthwlock/untrunc#49]
Thank you so much for maintaining this fork! 

I've got an issue with server shutting down during RTMP recording and now trying to recover the mp4 file, however getting some errors that are hard to decode, and not found in this repository closed issues. 

Can you please clarify what some of them mean? It does look like recovery didn't work, unfortunately. Any recommendation?

untrunc# docker run -v ~/untrunc:/streams untrunc -s /streams/LIAGXQUE.mp4 /streams/EBYWVSIQ.mp4
WARNING: Because of internal decoder changes, using ffmpeg '3.4.6-0ubuntu0.18.04.1' with '-s' can be slow!
         You are advised to compile untrunc against ffmpeg 3.3!
         See the README.md on how to do that.
Info: version '7e38461-dirty' using ffmpeg '3.4.6-0ubuntu0.18.04.1'
Info: reading /streams/LIAGXQUE.mp4
Info: parsing healthy moov atom ...
Warning: avcC was not decoded correctly

Info: reading mdat from truncated file ...
Info: Muted ffmpeg to reduce redundant warnings/errors. Use '-do' to see them.
Failed reading golomb: too large!
Warning: Invalid slice type, probably this is not an avc1 sample
Warning: Invalid slice type, probably this is not an avc1 sample
Warning: guessed frame durations of 'mp4a' will probably be wrong!
Warning: guessed frame durations of 'avc1' will probably be wrong!
Info: Found 77 packets ( mp4a: 0 avc1: 77 avc1-keyframes: 0 )
Info: Duration of mp4a:  (0 ms)
Info: Duration of avc1: 2s 376ms  (2376 ms)
Warning: Unknown sequences: 78
Warning: Bytes NOT matched: 260MiB (99.99%)
Info: pruned empty 'mp4a' track
Info: saving /streams/EBYWVSIQ.mp4_fixed-s1.mp4
Could not create file for writing: /streams/EBYWVSIQ.mp4_fixed-s1.mp4

**Here's ffprobe of healthy file:**

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'streams/LIAGXQUE.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.20.100
  Duration: 00:03:10.16, start: 0.000000, bitrate: 3144 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 32000 Hz, stereo, fltp, 65 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:1(und): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p, 1280x720, 3074 kb/s, 29.90 fps, 90k tbr, 90k tbn, 180k tbc (default)
    Metadata:
      handler_name    : VideoHandler

Thank you in advance

**Comment by mkrn** [comment]
Is there a way to manually set the codec? The settings are known, but bitrate and FPS may be variable...

Also, running without -s option:

Info: version '7e38461-dirty' using ffmpeg '3.4.6-0ubuntu0.18.04.1'
Info: reading /streams/LIAGXQUE.mp4
Info: parsing healthy moov atom ...
Warning: avcC was not decoded correctly

Info: reading mdat from truncated file ...
Could not create file for writing: /streams/EBYWVSIQ.mp4_fixed.mp4
Info: Muted ffmpeg to reduce redundant warnings/errors. Use '-do' to see them.
Error: unable to find correct codec -> premature end (~0%)
       try '-s' to skip unknown sequences

Warning: guessed frame durations of 'mp4a' will probably be wrong!
Warning: guessed frame durations of 'avc1' will probably be wrong!
Info: Found 0 packets ( mp4a: 0 avc1: 0 avc1-keyframes: 0 )
Info: Duration of mp4a:  (0 ms)
Info: Duration of avc1:  (0 ms)
Info: pruned empty 'mp4a' track
Info: pruned empty 'avc1' track
Info: saving /streams/EBYWVSIQ.mp4_fixed.mp4

**Comment by anthwlock** [comment]
Hi,
I am not sure if your corrupt file is similar to the reference one.
In the healthy file, `mp4a` often starts with `21 1b 8f ff ff ff`, avc1 often starts with `00 00 ?? ?? 41 ?? 10`.
Now I counted the number of occurrence:
```
# good.mp4
'\x00\x00..\x41'                    8437
'\x00\x00..\x41.\x10'               4150
'\x21\x1b\x8f\xff\xff\xff\xff'      133

# bad.mp4
'\x00\x00..\x41'                    15
'\x00\x00..\x41.\x10'               0
'\x21\x1b\x8f\xff\xff\xff\xff'      0
```

The errors basically mean that it didn't found the patterns it looked for.
