### ISSUE TITLE
Info: unknown track 'hev1' found -> fallback to dynamic stats Error: bad track: 'hev1'

### ISSUE THREAD

**Issue by muyangren907** [anthwlock/untrunc#50]
The following error occurred when I fixed the video on Ubuntu 18.04

Info: version '71d1a65' using ffmpeg '3.3.9'
Info: reading 2020_05_28_23_23_46.mp
Info: parsing healthy moov atom ... 
Composition time offset atom found. Out of order samples possible.

Info: unknown track 'hev1' found -> fallback to dynamic stats
Error: bad track: 'hev1'

**Comment by anthwlock** [comment]
Hi,
`hev1` is a new track, and I will need the files (healthy+broken) to add support for it.
If lucky, same code as for `hvc1` can be used.

<details>
  <summary>How to upload</summary>

  https://wetransfer.com/ offers hosting <2GB files for 7days, without registration.
  If your files are larger, `untrunc -sh file.mp4` lets you extract the first 200MB. 
</details>

**Comment by chenbb16** [comment]
@anthwlock I have the same problem. Can you help me?
I compress the files (healthy+broken)  into test.zip
I'm using Firefox Send, which will expire after two downloads or seven days
https://send.firefox.com/download/d66a4ac958c5090a/#V7FwdpVr0LidpOgRWGPHwA

**Comment by chenbb16** [comment]
> @anthwlock I have the same problem. Can you help me?
> I compress the files (healthy+broken) into test.zip
> I'm using Firefox Send, which will expire after two downloads or seven days
> https://send.firefox.com/download/d66a4ac958c5090a/#V7FwdpVr0LidpOgRWGPHwA
I have another broken video in
https://send.firefox.com/download/34ea06655304f365/#SHsCUvpIOtg4SHaj7xfstw

**Comment by anthwlock** [comment]
try 02c60464b7dc7a3c604d8d979327d29bf3f1602e

**Comment by chenbb16** [comment]
First of all, thanks a lot for your help!Most of the video has been fixed, but I still have some problems, although I use the -sv, video and audio still don't seem to match.

**Comment by muyangren907** [comment]
> try [02c6046](https://github.com/anthwlock/untrunc/commit/02c60464b7dc7a3c604d8d979327d29bf3f1602e)

Thank you very much. My video has been successfully fixed, but some parts of the video do not match the sound

**Comment by anthwlock** [comment]
The problem is that in some files the packet/frame duration is not constant.
AFAIK ffmpeg [doesn't](https://github.com/ponchio/untrunc/issues/141) report the correct duration..

You can see the durations by using `untrunc -d good.mp4 | grep hev1`, observe the last column.

When untrunc detects this, it will issue the following warning:
`Warning: guessed frame durations of 'hev1' will probably be wrong!`

**Comment by muyangren907** [comment]
Thank you for your help!
