### ISSUE TITLE
How to compile Windows GUI? Can I compile it under Ubuntu？

### ISSUE THREAD

**Issue by xdli16** [anthwlock/untrunc#52]
How to compile Windows GUI? Can I compile it under Ubuntu？

**Comment by anthwlock** [comment]
yes, see https://github.com/anthwlock/untrunc#gui

**Comment by xdli16** [comment]
I uploaded the broken video files again. This time, I compressed them into multiple compressed packages. If you need, you can download them again
https://send.firefox.com/download/06a198da8e19ed01/#OeI7OW2oNO6ztQjEg8fBNg
https://send.firefox.com/download/69982cfa1afb86e3/#cJ2koXa_OI0OK_Y82uohDA
https://send.firefox.com/download/ed62abaeeb109128/#UUanGayDSUgYu8AySNbS_g
