### ISSUE TITLE
track 'mp4v' is not supported with ffmpeg > 3.3!

### ISSUE THREAD

**Issue by skerit** [anthwlock/untrunc#53]
Here's the error I'm getting:

```
Info: version '56aee28' using ffmpeg 'n4.2.3'
Info: reading voy_101_000_2.00x_1440x1152_Gaia-HQ.mp4
Info: parsing healthy moov atom ... 

Error: track 'mp4v' is not supported with ffmpeg > 3.3!
Help: You need to build against ffmpeg 3.3.
      See the README.md on how to do that.
```

I need an older ffmpeg version for it to work?

**Comment by anthwlock** [comment]
Yes, see [this](https://github.com/anthwlock/untrunc/issues/37#issuecomment-576028249) comment for more info.
One would have add own parsing logic, as it's done for avc1 (aka h264).
