### ISSUE TITLE
interested in a snap version? 

### ISSUE THREAD

**Issue by michaelpeeters** [anthwlock/untrunc#54]
Hi, I used the `Dockerfile` as a basis to create a snapcraft.yaml for your untrunc version. 

snaps offer the advantage that they are automatically updated to the latest version. 

As an added benefit, snapcraft.io can automatically build new snap versions on their infrastructure whenever there is a change on the github repo.

**Comment by anthwlock** [comment]
Thank you.
I have added a snapcrat.yaml in d7e047d575c9, based on your snapcraft.yaml.

Do you know of a way to cache a partial result, so it doesn't need to be rebuild every time?
In this case, ~90% of the time is spent building ffmpeg.. which never changes.

**Comment by michaelpeeters** [comment]
Hi, unfortunately, my Makefile experience is a bit dusty from 20 years
ago...

But I went the lazy route and created the webhook to git & let snapcraft
build the snap on every change.

https://snapcraft.io/blog/we-are-changing-the-way-you-build-snaps-from-github-repos

**Comment by anthwlock** [comment]
Yes, I also meant the snapcraft build service, the Makefile is fine.
I thought maybe if one adds a separate 'part' for ffmpeg (in the snapcraft.yaml), with correct `parts.<part-name>.source`, it would be smart enough to cache the result.

Does your webhook use 'build.snapcraft.io' or just 'snapcraft.io'?

**Comment by michaelpeeters** [comment]
in my git history, my first attempt was to use the default ffmpeg as a
dynamic dependency:
https://github.com/michaelpeeters/untrunc/commit/3ebf1386b4f679e34e4d68b5b29f1c0872478432?diff=split#diff-184032a532406b07009403e26f4fc62f

This seemed to work, but I was puzzled with the remark in the readme that
ffmeg 3.3.9 works best. That's why the latest version of snapcraft.yaml
downloads ffmpeg3.3.9 & builds it back again.

I just followed the instructions on snapcraft.io for building:
[image: Screenshot_2020-06-21_19-18-51.png]

this creates a webhook on github:
[image: Screenshot_2020-06-21_19-29-00.png]
I only have to manage the release after a build on snapcraft.io

**Comment by anthwlock** [comment]
ffmpeg > 3.3 doesn't report video frame boundaries, see [here](https://github.com/anthwlock/untrunc/issues/37#issuecomment-576028249).

The screenshots are not visible, it's just text.
I also followed the instructions, and it automatically created a webhook to 'build.snapcraft.io', while the blog recommends just 'snapcraft.io'.
But since it works, I think I will leave it.

You don't know of a way to automatically promote edge releases to stable, do you?

**Comment by michaelpeeters** [comment]
I tried to find a solution for the "autopromote" to edge, but there doesn't
seem to be a simple solution.

It is possible to script the snapcraft release command, but that's not that
straightforward. :
https://ubuntu.com/blog/controlling-snap-releases-with-channels-tracks-and-branches-part-2

**Comment by anthwlock** [comment]
It looks like the link describes how to use an external build-service.
So it's not really applicable when using their 'build.snapcraft.io' service, right?

**Comment by michaelpeeters** [comment]
Hi, I was looking to the "Architecture" parameter of snapcraft release, but
in fact I just realized that every revision number is unique over
architectures:

e.g.:

snapcraft status michaelp-anthwlock-untrunc
Track    Arch     Channel    Version    Revision
latest   amd64    stable     1.0-git    14
                  candidate  1.0-git    14
                  beta       1.0-git    14
                  edge       1.0-git    14
         arm64    stable     1.0-git    9
                  candidate  1.0-git    9
                  beta       1.0-git    9
                  edge       1.0-git    19
         armhf    stable     1.0-git    8
                  candidate  1.0-git    8
                  beta       1.0-git    8
                  edge       1.0-git    18
         i386     stable     1.0-git    16
                  candidate  1.0-git    16
                  beta       1.0-git    16
                  edge       1.0-git    16
         ppc64el  stable     1.0-git    17
                  candidate  1.0-git    6
                  beta       1.0-git    6
                  edge       1.0-git    17
         s390x    stable     1.0-git    15
                  candidate  1.0-git    15
                  beta       1.0-git    15
                  edge       1.0-git    15

>> revision 19 is unique to arm64

so i can promote it:
snapcraft release michaelp-anthwlock-untrunc 19 stable
Track    Arch    Channel    Version    Revision
latest   arm64   stable     1.0-git    19
                 candidate  1.0-git    9
                 beta       1.0-git    9
                 edge       1.0-git    19


Now, If I understand snapcraft correctly, the idea would be to use
"channels" sparsely only when it makes sense, so closing irrelevant
channels might be more logical:

snapcraft close michaelp-anthwlock-untrunc candidate
Track    Arch     Channel    Version    Revision
latest   amd64    stable     1.0-git    14
                  candidate  ↑          ↑
                  beta       1.0-git    14
                  edge       1.0-git    14
         arm64    stable     1.0-git    19
                  candidate  ↑          ↑
                  beta       1.0-git    9
                  edge       1.0-git    19
         armhf    stable     1.0-git    8
                  candidate  ↑          ↑
                  beta       1.0-git    8
                  edge       1.0-git    18
         i386     stable     1.0-git    16
                  candidate  ↑          ↑
                  beta       1.0-git    16
                  edge       1.0-git    20
         ppc64el  stable     1.0-git    17
                  candidate  ↑          ↑
                  beta       1.0-git    6
                  edge       1.0-git    17
         s390x    stable     1.0-git    15
                  candidate  ↑          ↑
                  beta       1.0-git    15
                  edge       1.0-git    21

The candidate channel is now closed.

If you have more recent builds on edge for example and you close the
channel, that version is lost:

snapcraft close michaelp-anthwlock-untrunc edge beta
Track    Arch     Channel    Version    Revision
latest   amd64    stable     1.0-git    14
                  candidate  ↑          ↑
                  beta       ↑          ↑
                  edge       ↑          ↑
         arm64    stable     1.0-git    19
                  candidate  ↑          ↑
                  beta       ↑          ↑
                  edge       ↑          ↑
         armhf    stable     1.0-git    8
                  candidate  ↑          ↑
                  beta       ↑          ↑
                  edge       ↑          ↑
         i386     stable     1.0-git    16
                  candidate  ↑          ↑
                  beta       ↑          ↑
                  edge       ↑          ↑
         ppc64el  stable     1.0-git    17
                  candidate  ↑          ↑
                  beta       ↑          ↑
                  edge       ↑          ↑
         s390x    stable     1.0-git    15
                  candidate  ↑          ↑
                  beta       ↑          ↑
                  edge       ↑          ↑


I put it all into a gist:
https://gist.github.com/michaelpeeters/edc1c521d823d4d734552b76af7535ad

it' a bit blunt without any checks but it does move all edge versions to
stable and closes all other channels:

./promote_snap_edge_to_release.sh michaelp-anthwlock-untrunc
Track    Arch    Channel    Version    Revision
latest   amd64   stable     1.0-git    24
                 candidate  ↑          ↑
                 beta       ↑          ↑
                 edge       1.0-git    24
Track    Arch    Channel    Version    Revision
latest   arm64   stable     1.0-git    29
                 candidate  ↑          ↑
                 beta       ↑          ↑
                 edge       1.0-git    29
Track    Arch    Channel    Version    Revision
latest   armhf   stable     1.0-git    28
                 candidate  ↑          ↑
                 beta       ↑          ↑
                 edge       1.0-git    28
Track    Arch    Channel    Version    Revision
latest   i386    stable     1.0-git    25
                 candidate  ↑          ↑
                 beta       ↑          ↑
                 edge       1.0-git    25
Track    Arch     Channel    Version    Revision
latest   ppc64el  stable     1.0-git    27
                  candidate  ↑          ↑
                  beta       ↑          ↑
                  edge       1.0-git    27
Track    Arch    Channel    Version    Revision
latest   s390x   stable     1.0-git    26
                 candidate  ↑          ↑
                 beta       ↑          ↑
                 edge       1.0-git    26
Track    Arch     Channel    Version    Revision
latest   amd64    stable     1.0-git    24
                  candidate  ↑          ↑
                  beta       ↑          ↑
                  edge       ↑          ↑
         arm64    stable     1.0-git    29
                  candidate  ↑          ↑
                  beta       ↑          ↑
                  edge       ↑          ↑
         armhf    stable     1.0-git    28
                  candidate  ↑          ↑
                  beta       ↑          ↑
                  edge       ↑          ↑
         i386     stable     1.0-git    25
                  candidate  ↑          ↑
                  beta       ↑          ↑
                  edge       ↑          ↑
         ppc64el  stable     1.0-git    27
                  candidate  ↑          ↑
                  beta       ↑          ↑
                  edge       ↑          ↑
         s390x    stable     1.0-git    26
                  candidate  ↑          ↑
                  beta       ↑          ↑
                  edge       ↑          ↑

The candidate, edge and beta channels are now closed.

Not sure if this script can be scheduled on snapcraft.io, but it surely
makes it easier to promote the snap version.

to be complete, I found a script that does the same but requires a bit more
input & does more validation:
https://github.com/kenvandine/snapcraft-utils/blob/master/snapcraft-promote.sh

Sorry for the loooong answer, but I hope this helps ,

Michaêl

**Comment by anthwlock** [comment]
> Not sure if this script can be scheduled on snapcraft.io, but it surely
makes it easier to promote the snap version.

That's my main concern, just a commit should be enough.
Is there any downside to not having a stable release, other than having to type `--edge`?

**Comment by michaelpeeters** [comment]
I'm not sure you can install a snap from the gui that is not on stable. I
will have to check it out later...

**Comment by anthwlock** [comment]
For testing you can use: https://snapcraft.io/untrunc-anthwlock

**Comment by michaelpeeters** [comment]
Hi Anthon,
You're right, the edge-channel-only approach doesn't seem to make a
difference in the Ubuntu Softwarecenter
it installed without warning & runs just fine
[image: Screenshot_2020-06-30_17-37-51.png]

**Comment by anthwlock** [comment]
Ok, thanks for testing.

Unless you plan on updating 'michaelp-anthwlock-untrunc' regularly, It would probably be best to shut it down.
People might think it is more stable (stable channel + '1.0' version), and it would cause confusion..
