### ISSUE TITLE
Error: no 'moov' atom found

### ISSUE THREAD

**Issue by mageddo** [anthwlock/untrunc#63]
```
docker run -v $PWD:/mnt untrunc-v3:v3 /mnt/2016_1119_113330_021.MOV
Info: version 'bf5727b-dirty' using ffmpeg '3.3.9'
Info: reading /mnt/2016_1119_113330_021.MOV
Info: parsing healthy moov atom ... 
Warning: bad 'mdat' length = 3828969872 new_pos = 3829177968
Warning: failed decoding atom: invalid atom name: '��I�'
Error: no 'moov' atom found
```

* Related to [this issue](https://github.com/ponchio/untrunc/issues/72)
* [The file used](https://drive.google.com/file/d/1lrUA02Z5AaYIpLdTE2_suJzHRoVAs6QD/view?usp=sharing)

**Comment by anthwlock** [comment]
```
$ untrunc
Usage: untrunc [options] <ok.mp4> [corrupt.mp4]
```
You are using 'corrupt.mp4' in place of 'ok.mp4'.

**Comment by mageddo** [comment]
Then I got it wrong, isn't untrunc about repairing corrupted videos? If I have the ok file then I don't need untrunc

**Comment by mageddo** [comment]
> You need both the broken video and an example working video (ideally from the same camera, if not the chances to fix it are slim).

Allright, got it. I'll give it a try

**Comment by numerized** [comment]
Thanks I made it work with this help!

**Comment by alexwaston0891** [comment]
Well, most of the time it may happen that due to incomplete downloading the video file can cause ‘**[moov atom not found](https://www.rescuedigitalmedia.com/fix-video-moov-atom-not-found-error)**’ error”. So to solve this issue, you need to download the footage file again from a reliable source. After that you can watch your favourite video without any interruption.

**Comment by dark-swordsman** [comment]
> So to solve this issue, you need to download the footage file again from a reliable source. After that you can watch your favourite video without any interruption.

This defeats the entire purpose of this program lol
