### ISSUE TITLE
Error: bad track: 'free'

### ISSUE THREAD

**Issue by psstpsstpsst** [anthwlock/untrunc#66]
I'm having an issue with this, I'm getting:

Info: version '644978f' using ffmpeg '3.3.9'
Info: reading 20151126_070833.MOV
Info: parsing healthy moov atom ... 
Composition time offset atom found. Out of order samples possible.

Info: unknown track 'sowt' found -> fallback to dynamic stats
Error: bad track: 'free'

Is it something that can be fixed or is it impossible?

Thank you very much for you work, really appreciate it.

**Comment by anthwlock** [comment]
If there is a way to predict start and length of those 'free' sequences, it is fixable.
The better the prediction the better the resulting file.

If you want me to take a look, send me your files (healthy + broken).

**Comment by psstpsstpsst** [comment]
Perfect, Anthon, I just did. 
Thanks a lot.

**Comment by anthwlock** [comment]
The main problems were:
  * unknown atoms, scattered in the mdat atom 015d0f112f945d5fa2e716b3616f1c7bdf9c81f3
  * false detection between avc1 and sowt. a17b173e9fa3ea91b79c8e5142e33f478bb4d7ef

The first one was easy to fix, the second was a little harder.
There were more problems, see commit history if interested..

**Comment by psstpsstpsst** [comment]
You are a master  :-)

Thank you!
