### ISSUE TITLE
Add support for ProRes 4444 and 4444 XQ (ap4h and ap4x)

### ISSUE THREAD

**Issue by cbenhagen** [anthwlock/untrunc#69]
Currently we get this error message:

```
Info: unknown track 'ap4x' found -> fallback to dynamic stats
Error: bad track: 'ap4x'
```

The sample I got here is confidential. Sending it to your mail address.

**Comment by anthwlock** [comment]
Try https://github.com/anthwlock/untrunc/tree/fz_16mib

**Comment by cbenhagen** [comment]
Awesome :) Thank you very much!
