### ISSUE TITLE
Apple ProRes / apco support..?

### ISSUE THREAD

**Issue by jahudka** [anthwlock/untrunc#75]
Hi, I have a bunch of files `*_ftyp.mov` files restored by `photorec` which I'm trying to recover using `untrunc`. I also have a sample file from the same camera; `ffprobe` reports that this file contains an Apple ProRes 422 video track (the codec tag string is `apco`). `untrunc` gives me this:

```
Info: unknown track 'apco' found -> fallback to dynamic stats
Error: bad track: 'apco'
```

Am I correct in assuming this means that the Apple ProRes codec isn't supported by `untrunc`? If I am, is there any chance that support could be added? I'd send the files, but they're both almost 20GB..

**Comment by anthwlock** [comment]
See #69 

The reason I didn't merged it yet is that it I had to increase the upper sample-size limit to 16mb, which adds more false positives for some files. I plan to replace this strict upper limit with a more dynamic one, which takes the average sample-size of the reference file in account.
