### ISSUE TITLE
snap install ~> Could not open file 

### ISSUE THREAD

**Issue by sangaman** [anthwlock/untrunc#80]
I'm unable to use `untrunc-anthrwlock` on Ubuntu 20.10, installed from snap store. When I try to use it on a known good video file and a known broken video file, I always get a `Could not open file` error on the first "good" file path I pass to the argument. I'm 100% certain the path is correct, the video is playable, and the permissions are fine (I've tried `sudo` for good measure). Any idea what is going on?

**Comment by anthwlock** [comment]
Probably a duplicate: https://github.com/anthwlock/untrunc/issues/73#issuecomment-727241597

You can leave this open though, so that I will remember to check if the `removable-media` can be added to `snapcraft.yaml`.

**Comment by sangaman** [comment]
Yes that was indeed the issue, moving all the files to my home folder made the problem go away. Sorry I didn't find the duplicate issue first.

**Comment by anthwlock** [comment]
Looks like I already added the `removable-media` plug, and it even seems to be working. So I am closing this, since I don't know of any further ways to allow wider access. In case someone finds anything, lmk.
