### ISSUE TITLE
could not open reference file

### ISSUE THREAD

**Issue by cocoBravebird** [anthwlock/untrunc#81]
could not open reference file
but i can open the reference file by videoplayer.
![image](https://user-images.githubusercontent.com/28882685/108621423-7948bf00-746d-11eb-8a3c-91742719674f.png)

**Comment by anthwlock** [comment]
Maybe it has to do with the folder name. Could you try to move the file to a location so it's path only contains [ascii](https://en.wikipedia.org/wiki/ASCII#Character_set) characters?

**Comment by anthwlock** [comment]
Hopefully this got fixed with 122463354af1556662ebe0c7e0dece98aca56c07
