### ISSUE TITLE
Error: No codec found!

### ISSUE THREAD

**Issue by hipur** [anthwlock/untrunc#9]
Hi, I'm having the following error:

Info: reading /mnt/c/Users/purch/Desktop/recover/C0113.MP4
Info: parsing healthy moov atom ...

requests: 4 at offset : 0
requests: 4 at offset : 4
start_ = 0
length_ = 28
name_ = ftyp
requests: 20 at offset : 8

requests: 4 at offset : 28
requests: 4 at offset : 32
start_ = 28
length_ = 148
name_ = uuid
requests: 140 at offset : 36

requests: 4 at offset : 176
requests: 4 at offset : 180
requests: 8 at offset : 184
start_ = 184
length_ = 96468808
name_ = mdat

requests: 4 at offset : 0
requests: 4 at offset : 4
start_ = 96468992
length_ = 3981
name_ = moov

requests: 4 at offset : 8
requests: 4 at offset : 12
start_ = 96469000
length_ = 108
name_ = mvhd
requests: 100 at offset : 16

requests: 4 at offset : 116
requests: 4 at offset : 120
start_ = 96469108
length_ = 2706
name_ = trak

requests: 4 at offset : 124
requests: 4 at offset : 128
start_ = 96469116
length_ = 92
name_ = tkhd
requests: 84 at offset : 132

requests: 4 at offset : 216
requests: 4 at offset : 220
start_ = 96469208
length_ = 36
name_ = edts

requests: 4 at offset : 224
requests: 4 at offset : 228
start_ = 96469216
length_ = 28
name_ = elst
requests: 20 at offset : 232

requests: 4 at offset : 252
requests: 4 at offset : 256
start_ = 96469244
length_ = 2518
name_ = mdia

requests: 4 at offset : 260
requests: 4 at offset : 264
start_ = 96469252
length_ = 32
name_ = mdhd
requests: 24 at offset : 268

requests: 4 at offset : 292
requests: 4 at offset : 296
start_ = 96469284
length_ = 52
name_ = hdlr
requests: 44 at offset : 300

requests: 4 at offset : 344
requests: 4 at offset : 348
start_ = 96469336
length_ = 2426
name_ = minf

requests: 4 at offset : 352
requests: 4 at offset : 356
start_ = 96469344
length_ = 20
name_ = vmhd
requests: 12 at offset : 360

requests: 4 at offset : 372
requests: 4 at offset : 376
start_ = 96469364
length_ = 36
name_ = dinf

requests: 4 at offset : 380
requests: 4 at offset : 384
start_ = 96469372
length_ = 28
name_ = dref
requests: 20 at offset : 388

requests: 4 at offset : 408
requests: 4 at offset : 412
start_ = 96469400
length_ = 2362
name_ = stbl

requests: 4 at offset : 416
requests: 4 at offset : 420
start_ = 96469408
length_ = 462
name_ = stsd
requests: 454 at offset : 424

requests: 4 at offset : 878
requests: 4 at offset : 882
start_ = 96469870
length_ = 24
name_ = stts
requests: 16 at offset : 886

requests: 4 at offset : 902
requests: 4 at offset : 906
start_ = 96469894
length_ = 976
name_ = ctts
requests: 968 at offset : 910

requests: 4 at offset : 1878
requests: 4 at offset : 1882
start_ = 96470870
length_ = 28
name_ = stsc
requests: 20 at offset : 1886

requests: 4 at offset : 1906
requests: 4 at offset : 1910
start_ = 96470898
length_ = 740
name_ = stsz
requests: 732 at offset : 1914

requests: 4 at offset : 2646
requests: 4 at offset : 2650
start_ = 96471638
length_ = 76
name_ = stco
requests: 68 at offset : 2654

requests: 4 at offset : 2722
requests: 4 at offset : 2726
start_ = 96471714
length_ = 48
name_ = stss
requests: 40 at offset : 2730

requests: 4 at offset : 2770
requests: 4 at offset : 2774
start_ = 96471762
length_ = 52
name_ = uuid
requests: 44 at offset : 2778

requests: 4 at offset : 2822
requests: 4 at offset : 2826
start_ = 96471814
length_ = 560
name_ = trak

requests: 4 at offset : 2830
requests: 4 at offset : 2834
start_ = 96471822
length_ = 92
name_ = tkhd
requests: 84 at offset : 2838

requests: 4 at offset : 2922
requests: 4 at offset : 2926
start_ = 96471914
length_ = 36
name_ = edts

requests: 4 at offset : 2930
requests: 4 at offset : 2934
start_ = 96471922
length_ = 28
name_ = elst
requests: 20 at offset : 2938

requests: 4 at offset : 2958
requests: 4 at offset : 2962
start_ = 96471950
length_ = 372
name_ = mdia

requests: 4 at offset : 2966
requests: 4 at offset : 2970
start_ = 96471958
length_ = 32
name_ = mdhd
requests: 24 at offset : 2974

requests: 4 at offset : 2998
requests: 4 at offset : 3002
start_ = 96471990
length_ = 52
name_ = hdlr
requests: 44 at offset : 3006

requests: 4 at offset : 3050
requests: 4 at offset : 3054
start_ = 96472042
length_ = 280
name_ = minf

requests: 4 at offset : 3058
requests: 4 at offset : 3062
start_ = 96472050
length_ = 16
name_ = smhd
requests: 8 at offset : 3066

requests: 4 at offset : 3074
requests: 4 at offset : 3078
start_ = 96472066
length_ = 36
name_ = dinf

requests: 4 at offset : 3082
requests: 4 at offset : 3086
start_ = 96472074
length_ = 28
name_ = dref
requests: 20 at offset : 3090

requests: 4 at offset : 3110
requests: 4 at offset : 3114
start_ = 96472102
length_ = 220
name_ = stbl

requests: 4 at offset : 3118
requests: 4 at offset : 3122
start_ = 96472110
length_ = 52
name_ = stsd
requests: 44 at offset : 3126

requests: 4 at offset : 3170
requests: 4 at offset : 3174
start_ = 96472162
length_ = 24
name_ = stts
requests: 16 at offset : 3178

requests: 4 at offset : 3194
requests: 4 at offset : 3198
start_ = 96472186
length_ = 40
name_ = stsc
requests: 32 at offset : 3202

requests: 4 at offset : 3234
requests: 4 at offset : 3238
start_ = 96472226
length_ = 20
name_ = stsz
requests: 12 at offset : 3242

requests: 4 at offset : 3254
requests: 4 at offset : 3258
start_ = 96472246
length_ = 76
name_ = stco
requests: 68 at offset : 3262

requests: 4 at offset : 3330
requests: 4 at offset : 3334
start_ = 96472322
length_ = 52
name_ = uuid
requests: 44 at offset : 3338

requests: 4 at offset : 3382
requests: 4 at offset : 3386
start_ = 96472374
length_ = 553
name_ = trak

requests: 4 at offset : 3390
requests: 4 at offset : 3394
start_ = 96472382
length_ = 92
name_ = tkhd
requests: 84 at offset : 3398

requests: 4 at offset : 3482
requests: 4 at offset : 3486
start_ = 96472474
length_ = 20
name_ = tref

requests: 4 at offset : 3490
requests: 4 at offset : 3494
start_ = 96472482
length_ = 12
name_ = cdsc
requests: 4 at offset : 3498

requests: 4 at offset : 3502
requests: 4 at offset : 3506
start_ = 96472494
length_ = 36
name_ = edts

requests: 4 at offset : 3510
requests: 4 at offset : 3514
start_ = 96472502
length_ = 28
name_ = elst
requests: 20 at offset : 3518

requests: 4 at offset : 3538
requests: 4 at offset : 3542
start_ = 96472530
length_ = 345
name_ = mdia

requests: 4 at offset : 3546
requests: 4 at offset : 3550
start_ = 96472538
length_ = 32
name_ = mdhd
requests: 24 at offset : 3554

requests: 4 at offset : 3578
requests: 4 at offset : 3582
start_ = 96472570
length_ = 61
name_ = hdlr
requests: 53 at offset : 3586

requests: 4 at offset : 3639
requests: 4 at offset : 3643
start_ = 96472631
length_ = 244
name_ = minf

requests: 4 at offset : 3647
requests: 4 at offset : 3651
start_ = 96472639
length_ = 12
name_ = nmhd
requests: 4 at offset : 3655

requests: 4 at offset : 3659
requests: 4 at offset : 3663
start_ = 96472651
length_ = 36
name_ = dinf

requests: 4 at offset : 3667
requests: 4 at offset : 3671
start_ = 96472659
length_ = 28
name_ = dref
requests: 20 at offset : 3675

requests: 4 at offset : 3695
requests: 4 at offset : 3699
start_ = 96472687
length_ = 188
name_ = stbl

requests: 4 at offset : 3703
requests: 4 at offset : 3707
start_ = 96472695
length_ = 32
name_ = stsd
requests: 24 at offset : 3711

requests: 4 at offset : 3735
requests: 4 at offset : 3739
start_ = 96472727
length_ = 24
name_ = stts
requests: 16 at offset : 3743

requests: 4 at offset : 3759
requests: 4 at offset : 3763
start_ = 96472751
length_ = 28
name_ = stsc
requests: 20 at offset : 3767

requests: 4 at offset : 3787
requests: 4 at offset : 3791
start_ = 96472779
length_ = 20
name_ = stsz
requests: 12 at offset : 3795

requests: 4 at offset : 3807
requests: 4 at offset : 3811
start_ = 96472799
length_ = 76
name_ = stco
requests: 68 at offset : 3815

requests: 4 at offset : 3883
requests: 4 at offset : 3887
start_ = 96472875
length_ = 52
name_ = uuid
requests: 44 at offset : 3891

requests: 4 at offset : 3935
requests: 4 at offset : 3939
start_ = 96472927
length_ = 46
name_ = uuid
requests: 38 at offset : 3943

requests: 4 at offset : 3981
requests: 4 at offset : 3985
start_ = 96472973
length_ = 1520
name_ = meta
requests: 1512 at offset : 3989
Composition time offset atom found. Out of order samples possible.
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/mnt/c/Users/purch/Desktop/recover/C0113.MP4':
  Metadata:
    major_brand     : XAVC
    minor_version   : 16785407
    compatible_brands: XAVCmp42iso2
    creation_time   : 2018-09-19T00:40:55.000000Z
  Duration: 00:00:07.51, start: 0.000000, bitrate: 102769 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, unknown/unknown/bt709), 3840x2160 [SAR 1:1 DAR 16:9], 96970 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      creation_time   : 2018-09-19T00:40:55.000000Z
      handler_name    : Video Media Handler
      encoder         : AVC Coding
    Stream #0:1(und): Audio: pcm_s16be (twos / 0x736F7774), 48000 Hz, 2 channels, s16, 1536 kb/s (default)
    Metadata:
      creation_time   : 2018-09-19T00:40:55.000000Z
      handler_name    : Sound Media Handler
    Stream #0:2(und): Data: none (rtmd / 0x646D7472), 196 kb/s (default)
    Metadata:
      creation_time   : 2018-09-19T00:40:55.000000Z
      handler_name    : Timed Metadata Media Handler
      timecode        : 13:35:47:00
found avcC after: 102
remaining len:360
parsing avcC ...
len_sps: 52
decoding SPS ...
log2_max_frame_num: 6
Info: avcC got decoded
No codec found!

My reference file and damaged file are generated from a Sony A7RIII and I have the according XMLs.
The reference file plays just great.

Do you have any clues on how to fix this?

**Comment by anthwlock** [comment]
Please send me the files, otherwise I can't help you.

**Comment by garnio** [comment]
Same issue here, my file is 18Gb XAVC-S 100fps

**Comment by anthwlock** [comment]
@garnio could you send me a healthy sample, around 100mb or so?

**Comment by garnio** [comment]
Thanks anthwlock! I gave up on this app, I did found another one called restore_mp4 that creates an h264 file and a wave file, combined in ffmpeg it works perfectly!

**Comment by anthwlock** [comment]
@garnio do you have the url? I am unable to find such a program.

**Comment by garnio** [comment]
https://tehnoblog.org/video-repair-guide-corrupted-mp4-avi-h264-file-fix/

the official program is no longer available, the developer got sick at people using his program without giving any donation, now he provides an automatic service but you have to pay. in the link I provided you can find the deprecated tool, it worked perfectly for me.
In addition you need a compiled version of ffmpeg version 3.4.1 or something like that.
