### ISSUE TITLE
Error: unable to find correct codec -> premature end (~0%)

### ISSUE THREAD

**Issue by Utopolis** [anthwlock/untrunc#92]
Hi,

I have some trouble with files that I send you by email. I would like to know if you could help to find why I can't read this file. I can give you the method that I used :

1) launch in the command line :
openRTSP -D 1 -c -B 10000000 -b 10000000 -q -Q -F cam_X -d 28800 -P 900 -t "rtsp:link"

2) Break the capture before the end

the logs are :
[h264 @ 0x55f3287fec80] no frame!
[h264 @ 0x55f3287fec80] no frame!
[h264 @ 0x55f3287fec80] no frame!
Info: version '3cf5947-dirty' using ffmpeg '3.4.8-0ubuntu0.2'
Info: reading /mnt/cam_eight-00000-00010.mov
Info: parsing healthy moov atom ... 

Info: unknown track 'alaw' found -> fallback to dynamic stats
Info: using dynamic stats, use '-is' to see them
Info: reading mdat from truncated file ...
no half-pattern suggests this ..
Error: unable to find correct codec -> premature end (~0%)
       try '-s' to skip unknown sequences

Info: Found 0 packets ( avc1: 0 avc1-keyframes: 0 alaw: 0 )
Info: Duration of avc1:  (0 ms)
Info: Duration of alaw:  (0 ms)
Info: pruned empty 'avc1' track
Info: pruned empty 'alaw' track
Info: saving /mnt/corrupt.mov_fixed-dyn.mov

Thanks a lot a lot for your help !

**Comment by anthwlock** [comment]
The files you send me can be recovered after 2ac1390c44f7416535a6edf5cdc19a6d8906aa23
